version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:014498631401:task-definition/production-task:3
        LoadBalancerInfo:
          ContainerName: "spring-petclinic"
          ContainerPort: 8080
