name: Deploy to ECS

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for building multi-platform Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log into AWS ECR (using GitHub Secrets)
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push Docker image to ECR
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.ECR_REPOSITORY_URI }}:$GITHUB_SHA .
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:$GITHUB_SHA

      # Deploy to ECS (using GitHub Secrets)
      - name: Deploy to ECS
        uses: jakejarvis/aws-ecs-deploy-action@v1
        with:
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          service: ${{ secrets.ECS_SERVICE_NAME }}
          image: ${{ secrets.ECR_REPOSITORY_URI }}:$GITHUB_SHA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
